services:
  follow-claim:
    container_name: follow-claim
    image: missuo/follow-claim:latest
    restart: unless-stopped
    environment:
      # Cookie (Required)
      - COOKIE=
      # User ID (Required)
      - USER_ID=
      # Bark URL (Optional)
      - BARK_URL=
      # Use UTC Time (UTC 00:05 is 08:05 in China) (Optional, Default: 00:05)
      - SCHEDULED_TIME=00:05
      # Timezone offset (Optional, Default: 8)
      - TIMEZONE_OFFSET=8
      # Telegram Token (Optional)
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
      # en：Whether to run immediately after running(Optional, Default: false, eg: true/false)
      - IS_RUN_IMMEDIATELY=false